
- name: User hadoop
  become: yes
  import_tasks: ./user-hadoop.yml

- name: Dowload hadoop
  become: yes
  import_tasks: ./dowload-hadoop.yml

- name: Config hadoop
  become: yes
  import_tasks: ./config-hadoop.yml

- name: Change hadoop files permission
  become: yes
  shell: chown -R hadoop:hadoop {{hadoop_home}}

- name: Format namenode
  become: yes
  command: "{{hadoop_home}}/bin/hdfs namenode -format"