- name: Add the user {{user_name}}
  user:
    name: "{{user_name}}"
    password: "{{user_password}} | password_hash('sha512') }}"
    shell: /bin/bash

- name: Create a directory ".ssh"
  file:
    path: "/home/{{user_name}}/.ssh/"
    state: directory

- name: Create file - id_rsa.pub
  copy:
    src: ../../key/id_rsa.pub
    dest: "/home/{{user_name}}/.ssh/"
    mode: 0600

- name: Create file - id_rsa
  copy:
    src: ../../key/id_rsa
    dest: "/home/{{user_name}}/.ssh/"
    mode: 0600

- name: Create file - authorized_keys
  shell: "cat /home/{{user_name}}/.ssh/id_rsa.pub > /home/{{user_name}}/.ssh/authorized_keys"
  args:
    executable: /bin/bash

- name: Export Key - Public
  fetch:
    src: "/home/{{user_name}}/.ssh/id_rsa.pub"
    dest: ../../key/id_rsa.pub
    flat: yes

- name: Export Key - Key
  fetch:
    src: "/home/{{user_name}}/.ssh/id_rsa"
    dest: ../../key/id_rsa
    flat: yes

- name: Create known_hosts - localhost
  shell: "ssh-keyscan -H localhost >> /home/{{user_name}}/.ssh/known_hosts"

- name: Create known_hosts - hadoop-master
  shell: "ssh-keyscan -H hadoop-master >> /home/{{user_name}}/.ssh/known_hosts"

- name: Change hadoop files permission
  shell: "chown -R {{user_name}}:{{user_name}} /home/hadoop"
