- name: Add the user 'hadoop'
  user:
    name: hadoop
    password: "{{ 'password' | password_hash('sha512') }}"
    comment: hadoop
    shell: /bin/bash

- name: Create a directory ".ssh"
  file:
    path: /home/hadoop/.ssh/
    state: directory

- name: Create file - id_rsa.pub
  copy:
    src: ../../key/id_rsa.pub
    dest: /home/hadoop/.ssh/
    mode: 0600

- name: Create file - id_rsa
  copy:
    src: ../../key/id_rsa
    dest: /home/hadoop/.ssh/
    mode: 0600

- name: Create file - authorized_keys
  shell: cat /home/hadoop/.ssh/id_rsa.pub > /home/hadoop/.ssh/authorized_keys
  args:
    executable: /bin/bash

- name: Export Key - Public
  fetch:
    src: /home/hadoop/.ssh/id_rsa.pub
    dest: ../../key/id_rsa.pub
    flat: yes

- name: Export Key - Key
  fetch:
    src: /home/hadoop/.ssh/id_rsa
    dest: ../../key/id_rsa
    flat: yes

- name: Create known_hosts - localhost
  shell: ssh-keyscan -H localhost >> /home/hadoop/.ssh/known_hosts

- name: Create known_hosts - hadoop-master
  shell: ssh-keyscan -H hadoop-master >> /home/hadoop/.ssh/known_hosts


- name: Change hadoop files permission
  shell: chown -R hadoop:hadoop /home/hadoop
